DEPENDENCIES: dict[str, list[dict]] = {

    "ssl_score": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.1,
            "reason": "O site existe há muitos anos e o certificado de segurança parece irregular. Isso provavelmente é só uma configuração técnica desatualizada, não um sinal de perigo real.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.3},
            "action": "reduce",
            "factor": 0.35,
            "reason": "O site já está no ar há bastante tempo e tem um certificado de segurança mediano. Sites estabelecidos assim costumam ter infraestrutura confiável, mesmo que o certificado não seja perfeito.",
        },
        {
            "depends_on": "dns_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "Apesar do certificado de segurança não ser ideal, o sistema de endereços do site (DNS) está saudável. Isso indica que a infraestrutura é legítima e o problema no certificado é provavelmente pontual.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.35,
            "reason": "O nome do site é reconhecível e não parece gerado automaticamente. Um certificado suspeito num site assim provavelmente é só um erro de configuração, não uma tentativa de fraude.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.5,
            "reason": "O site foi criado recentemente e não tem um certificado de segurança válido. Sites de phishing novos costumam não ter tempo ou interesse em configurar segurança adequada.",
        },
        {
            "depends_on": "dns_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "Além do certificado inválido, o sistema de endereços do site também está comprometido. Dois problemas de infraestrutura juntos é um sinal forte de que o site não é confiável.",
        },
        {
            "depends_on": "ip_in_url",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.4,
            "reason": "O link usa um número de IP no lugar de um nome de domínio, e o certificado de segurança é inválido. Isso é típico de servidores descartáveis usados em golpes.",
        },
    ],

    "domain_age": [
        {
            "depends_on": "dns_score",
            "condition": {"op": "is_none"},
            "action": "skip",
            "reason": "Não foi possível verificar o sistema de endereços do site (DNS), então a idade do domínio não pode ser confirmada com segurança.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.4,
            "reason": "O site foi registrado recentemente e não tem certificado de segurança válido. Essa combinação é muito comum em páginas de phishing criadas às pressas.",
        },
        {
            "depends_on": "dns_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O domínio é novo e o sistema de endereços está mal configurado. Parece uma infraestrutura criada rapidamente para ser usada e descartada, o que é típico de golpes.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": ">=", "val": 0.6},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site é novo e o nome do domínio parece gerado automaticamente, sem sentido real. Isso é um padrão frequente em domínios criados por ferramentas automáticas para aplicar golpes.",
        },
        {
            "depends_on": "rdap_metadata_incompleteness",
            "condition": {"op": ">=", "val": 0.6},
            "action": "increase",
            "factor": 1.2,
            "reason": "O domínio é recente e as informações de registro estão ocultadas ou incompletas. Quem registra um site novo e já esconde os dados geralmente tem algo a esconder.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "Apesar do site ser novo, ele tem um certificado de segurança válido emitido por uma autoridade reconhecida. Isso sugere um serviço legítimo que acabou de ser lançado.",
        },
        {
            "depends_on": "dns_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.45,
            "reason": "Mesmo sendo um domínio novo, o sistema de endereços está bem configurado. Sites legítimos recém-lançados costumam ter essa característica.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O domínio é novo, mas o nome é reconhecível e faz sentido. Pode ser simplesmente um produto ou serviço que acabou de entrar no ar.",
        },
    ],

    "dns_score": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O sistema de endereços parece incomum, mas o site existe há muitos anos. Sites antigos grandes costumam ter configurações DNS não convencionais por usar serviços de distribuição de conteúdo.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.3},
            "action": "reduce",
            "factor": 0.5,
            "reason": "O DNS tem algumas irregularidades, mas o site já está no ar há bastante tempo. Isso pode ser só uma configuração diferente do padrão, não necessariamente perigosa.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.15},
            "action": "reduce",
            "factor": 0.25,
            "reason": "O DNS não tem configuração de e-mail, mas o certificado de segurança está completamente válido. Isso é comum em sites simples que não usam e-mail mas têm conexão segura.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O nome do domínio é reconhecível, mesmo com DNS irregular. Empresas legítimas às vezes usam configurações de rede não convencionais.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.9},
            "action": "increase",
            "factor": 1.4,
            "reason": "O sistema de endereços e o certificado de segurança estão ambos completamente comprometidos. Quando dois pilares básicos da infraestrutura falham juntos, o risco é muito alto.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.7},
            "action": "increase",
            "factor": 1.2,
            "reason": "O DNS está suspeito e o certificado de segurança é inválido. Esses dois problemas juntos reforçam a ideia de que a infraestrutura do site não foi configurada de forma responsável.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O domínio é novo e o sistema de endereços está mal configurado. Isso sugere uma infraestrutura montada rapidamente, sem preocupação com confiabilidade.",
        },
        {
            "depends_on": "ip_in_url",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O link usa um número de IP diretamente no lugar de um nome de domínio, e o DNS também está suspeito. Isso indica um servidor sem identidade verificável.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": ">=", "val": 0.6},
            "action": "increase",
            "factor": 1.2,
            "reason": "O DNS está suspeito e o nome do domínio parece gerado automaticamente. Esse padrão é comum em domínios criados por algoritmos para fins maliciosos.",
        },
        {
            "depends_on": "random_path_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.15,
            "reason": "O DNS está suspeito e o caminho da URL também parece aleatório. Juntos, indicam um servidor mal-intencionado com URL construída para escapar de filtros de segurança.",
        },
    ],

    "rdap_metadata_incompleteness": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.2,
            "reason": "O domínio é muito antigo e as informações de registro estão incompletas. Isso provavelmente aconteceu porque o dono optou por privacidade depois de anos, o que é comum e legítimo.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "As informações de registro estão ocultas, mas o certificado de segurança é válido. Muitas pessoas e empresas legítimas optam por esconder dados de registro por privacidade.",
        },
        {
            "depends_on": "dns_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.45,
            "reason": "O registro está incompleto, mas o sistema de endereços funciona bem. Serviços legítimos frequentemente usam proteção de privacidade no registro sem que isso seja um problema.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.4,
            "reason": "O domínio foi registrado recentemente e as informações do dono estão ocultas. Registrar um site novo já escondendo a identidade é um padrão muito comum em golpes de phishing.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O registro está incompleto e o certificado de segurança é inválido. Sem identidade verificável e sem segurança adequada, o site não tem nenhum sinal de confiabilidade.",
        },
        {
            "depends_on": "nameserver_diversity",
            "condition": {"op": ">=", "val": 0.7},
            "action": "increase",
            "factor": 1.2,
            "reason": "O registro está incompleto e o site usa apenas um servidor de nomes básico. Isso sugere uma infraestrutura mínima e descartável, sem investimento real.",
        },
    ],

    "nameserver_diversity": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O site usa poucos servidores de nomes, mas existe há muitos anos. Sites antigos frequentemente consolidam toda a infraestrutura num único provedor por conveniência.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.3},
            "action": "reduce",
            "factor": 0.4,
            "reason": "Há poucos servidores de nomes, mas o site já é estabelecido. Usar um único provedor de DNS é uma escolha legítima e comum para simplificar a gestão.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O site usa poucos servidores de nomes, mas o certificado de segurança está válido. Serviços que usam CDN costumam centralizar o DNS sem que isso seja um problema.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.45,
            "reason": "O nome do domínio é reconhecível e usa poucos servidores de nomes. Isso é perfeitamente normal para serviços que preferem um único provedor de DNS confiável.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O domínio é novo e usa uma infraestrutura de DNS mínima. Sites criados para golpes costumam ter a configuração mais simples possível porque não pretendem durar muito tempo.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site usa poucos servidores de nomes e o certificado de segurança é inválido. Essa combinação de infraestrutura mínima sem segurança é típica de sites descartáveis.",
        },
        {
            "depends_on": "rdap_metadata_incompleteness",
            "condition": {"op": ">=", "val": 0.6},
            "action": "increase",
            "factor": 1.2,
            "reason": "O registro está incompleto e a infraestrutura de DNS é mínima. Esses dois fatores juntos tornam a identidade do site completamente opaca, o que é preocupante.",
        },
    ],

    "hyphen_risk": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O domínio tem hífens, mas existe há muitos anos. Nomes com hífens são comuns em marcas legítimas antigas, especialmente em sites descritivos.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.3},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O domínio usa hífens e já está estabelecido há algum tempo. Hífens em nomes descritivos são muito comuns em sites legítimos.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O domínio tem hífens, mas o certificado de segurança é válido. Isso sugere um site legítimo com nome descritivo, não um domínio gerado para enganar.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O domínio usa hífens, mas o nome tem sentido e baixa aleatoriedade. Hífens em nomes intencionais são um recurso normal de nomenclatura.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.25,
            "reason": "O domínio é novo e usa hífens. Sites de golpe frequentemente usam hífens para criar nomes que parecem legítimos, como 'banco-seguro-login.com'.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O domínio tem hífens e o nome parece gerado automaticamente. Essa combinação é um forte indicador de domínio criado por ferramenta automática para fins maliciosos.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.2,
            "reason": "O domínio tem hífens e o certificado de segurança é inválido. Parece um site descartável sem investimento real em infraestrutura.",
        },
        {
            "depends_on": "num_ratio_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.2,
            "reason": "O domínio combina hífens com muitos números no nome. Essa mistura é um padrão típico de domínios gerados automaticamente para campanhas de golpe.",
        },
    ],

    "at_risk": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.2,
            "reason": "O link contém o símbolo '@', mas o site é muito antigo. Esse caractere pode ser parte de uma autenticação interna legítima em sistemas estabelecidos.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.15},
            "action": "reduce",
            "factor": 0.3,
            "reason": "O link tem '@', mas o certificado de segurança está completamente válido. Isso pode ser uma autenticação básica legítima em um servidor seguro.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.5,
            "reason": "O link usa '@' em um domínio novo. Golpistas usam esse truque para esconder o destino real do link — tudo antes do '@' é ignorado pelo navegador, então o destino real é o que vem depois.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.7},
            "action": "increase",
            "factor": 1.4,
            "reason": "O link tem '@' e o certificado de segurança é inválido. Esse é um método clássico de ocultar para onde o link realmente aponta.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O link usa '@' num domínio com nome aleatório. Isso parece uma URL de phishing onde o destino real está deliberadamente escondido.",
        },
        {
            "depends_on": "ip_in_url",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.5,
            "reason": "O link combina '@' com um endereço IP no lugar do domínio. Esses dois elementos juntos são uma técnica conhecida para disfarçar completamente o destino de um link malicioso.",
        },
    ],

    "equal_risk": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.2,
            "reason": "O link tem parâmetros suspeitos com '=', mas o site é muito antigo. Em sites estabelecidos, isso geralmente são parâmetros normais de API ou rastreamento legítimo.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.35,
            "reason": "Há parâmetros suspeitos na URL, mas o certificado é válido. Parâmetros com '=' são normais em links de busca, filtros e outras funcionalidades comuns.",
        },
        {
            "depends_on": "mixed_encoding",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "A URL tem parâmetros suspeitos e também usa codificação misturada. Combinar essas técnicas é uma forma de esconder o conteúdo real dos parâmetros de sistemas de segurança.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site é novo e a URL tem parâmetros suspeitos. Em infraestruturas descartáveis usadas para golpes, parâmetros assim costumam carregar dados de ataque.",
        },
        {
            "depends_on": "xss_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "A URL tem parâmetros suspeitos e padrões que lembram ataques de injeção de código. Isso sugere uma tentativa de explorar vulnerabilidades via URL.",
        },
        {
            "depends_on": "query_contains_url",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "A URL contém um link escondido dentro de um parâmetro. Isso é uma técnica usada para redirecionar a vítima para outro site sem que ela perceba.",
        },
    ],

    "num_ratio_risk": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O nome do domínio tem muitos números, mas o site é muito antigo. Marcas e serviços legítimos antigos às vezes têm números no nome por razões históricas.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.3},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O domínio tem vários números, mas já existe há algum tempo. Números em domínios estabelecidos costumam ser identificadores intencionais.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O domínio tem muitos números, mas o certificado é válido. Serviços legítimos com nomes numéricos existem e são seguros.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O domínio tem números, mas o nome no geral é estruturado e faz sentido. Isso sugere uma escolha intencional de nome, não geração automática.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O domínio é novo e tem muitos números. Domínios gerados automaticamente para golpes frequentemente usam sequências numéricas aleatórias.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O domínio combina muitos números com alta aleatoriedade no nome. Esse perfil é muito semelhante ao de domínios gerados por algoritmos para campanhas maliciosas.",
        },
        {
            "depends_on": "hyphen_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.2,
            "reason": "O domínio mistura muitos números com hífens. Essa combinação é muito comum em nomes de domínio gerados automaticamente para fins de golpe.",
        },
    ],

    "mixed_encoding": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.2,
            "reason": "A URL usa tipos de codificação misturados, mas o site é muito antigo. Sites internacionais legítimos antigos às vezes têm essa característica por suporte a múltiplos idiomas.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.35,
            "reason": "A URL tem codificação misturada, mas o certificado é válido. Serviços legítimos que atendem usuários internacionais podem usar encodings diferentes.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.4,
            "reason": "O site é novo e a URL mistura diferentes tipos de codificação. Essa técnica é usada para confundir sistemas de segurança e esconder o conteúdo real do link.",
        },
        {
            "depends_on": "xss_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.5,
            "reason": "A URL tem codificação misturada e padrões de ataque de código. Combinar as duas técnicas é uma forma sofisticada de esconder ataques de filtros de segurança.",
        },
        {
            "depends_on": "base64_segment",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "A URL combina codificação misturada com dados em base64. Usar múltiplas camadas de codificação é uma técnica deliberada para ocultar o conteúdo real do link.",
        },
        {
            "depends_on": "at_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "A URL usa codificação misturada e o símbolo '@'. Essas duas técnicas juntas tornam muito difícil identificar para onde o link realmente aponta.",
        },
    ],

    "xss_risk": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.2,
            "reason": "A URL tem padrões que lembram ataques de código, mas o site é muito antigo. Em sites estabelecidos como mecanismos de busca, isso costuma ser um falso alarme.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.15},
            "action": "reduce",
            "factor": 0.3,
            "reason": "Há padrões suspeitos na URL, mas o certificado está completamente válido. Isso pode ser apenas um parâmetro de teste legítimo ou uma busca com caracteres especiais.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.4,
            "reason": "O site é novo e a URL contém padrões típicos de ataque de injeção de código. Isso sugere uma infraestrutura criada recentemente para explorar vulnerabilidades.",
        },
        {
            "depends_on": "mixed_encoding",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.5,
            "reason": "A URL combina padrões de ataque com codificação disfarçada. Essa é uma técnica avançada para esconder código malicioso de sistemas de proteção.",
        },
        {
            "depends_on": "query_contains_url",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "A URL tem padrões de ataque e também contém outro link escondido dentro dela. Isso é consistente com ataques que redirecionam a vítima enquanto executam código malicioso.",
        },
        {
            "depends_on": "equal_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "Há padrões de ataque na URL junto com parâmetros suspeitos. Isso indica uma tentativa estruturada de injetar código através dos parâmetros do link.",
        },
    ],

    "ip_in_url": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.2,
            "reason": "O link usa um número de IP, mas o domínio é muito antigo. Sistemas internos legítimos de empresas consolidadas às vezes usam IP diretamente para acesso interno.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.15},
            "action": "reduce",
            "factor": 0.25,
            "reason": "O link usa IP diretamente, mas o certificado de segurança é válido. Isso pode ser um serviço interno legítimo com certificado configurado para o IP.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.7},
            "action": "increase",
            "factor": 1.5,
            "reason": "O link usa um número de IP e o certificado de segurança é inválido. Esse servidor não tem nome de domínio nem segurança verificável, o que é muito arriscado.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.4,
            "reason": "O link usa IP e o domínio é novo. Servidores sem nome de domínio estabelecido são frequentemente usados em ataques porque são difíceis de rastrear.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.6,
            "reason": "O site pede uma senha e o link aponta para um endereço IP sem nome. Nunca é seguro inserir senhas em sites identificados apenas por um número de IP.",
        },
        {
            "depends_on": "random_path_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O link usa IP e o caminho da URL parece aleatório. Isso sugere um servidor anônimo com URL construída especificamente para escapar de detecção.",
        },
    ],

    "subdomain_count": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O site tem muitos subdomínios, mas é muito antigo. Plataformas de nuvem e grandes serviços estabelecidos costumam ter dezenas de subdomínios legítimos.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.35,
            "reason": "Há muitos subdomínios, mas o certificado é válido. Plataformas de nuvem legítimas costumam ter certificados wildcard que cobrem todos os subdomínios.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "O domínio tem muitos subdomínios, mas o nome é reconhecível. Grandes plataformas de tecnologia têm naturalmente uma estrutura com muitos subdomínios.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O domínio é novo e já tem muitos subdomínios. Golpistas que usam plataformas de nuvem costumam criar vários subdomínios rapidamente para distribuir ataques.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site tem muitos subdomínios e o certificado é inválido. Isso é um padrão comum em páginas de phishing hospedadas em serviços de nuvem sem configuração adequada.",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "O site tem muitos subdomínios e pelo menos um deles parece aleatório ou suspeito. Esse é um padrão conhecido de phishing em plataformas de nuvem.",
        },
        {
            "depends_on": "dns_score",
            "condition": {"op": ">=", "val": 0.6},
            "action": "increase",
            "factor": 1.2,
            "reason": "O site tem muitos subdomínios e o sistema de endereços não tem e-mail configurado. Sites descartáveis em nuvem frequentemente têm essa característica.",
        },
    ],

    "random_domain_risk": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.05,
            "reason": "O nome do domínio parece aleatório, mas o site existe há muitos anos. Marcas consolidadas, siglas e nomes técnicos podem parecer aleatórios mas são completamente legítimos.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.3},
            "action": "reduce",
            "factor": 0.2,
            "reason": "O domínio parece ter alta aleatoriedade, mas já está estabelecido há algum tempo. Provavelmente é uma marca legítima com nome não convencional.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.15},
            "action": "reduce",
            "factor": 0.2,
            "reason": "O nome do domínio parece aleatório, mas o certificado é completamente válido e emitido por uma autoridade reconhecida. Serviços legítimos obtêm esses certificados.",
        },
        {
            "depends_on": "dns_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.35,
            "reason": "O domínio parece aleatório, mas o DNS está bem configurado e tem e-mail. Empresas legítimas com nomes incomuns costumam ter essa infraestrutura saudável.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.4,
            "reason": "O domínio é recém-criado e o nome parece gerado automaticamente. Esse é um padrão muito comum em domínios criados por algoritmos para distribuir golpes em massa.",
        },
        {
            "depends_on": "dns_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.2,
            "reason": "O nome do domínio parece aleatório e a infraestrutura de DNS é mínima. Isso reforça a hipótese de um domínio descartável criado para uma campanha maliciosa.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.2,
            "reason": "O domínio parece aleatório e não tem certificado de segurança válido. Sem nome reconhecível e sem segurança, esse site não tem nenhum indicativo de legitimidade.",
        },
    ],

    "random_subdomain_risk": [
        {
            "depends_on": "subdomain_count",
            "condition": {"op": "is_none"},
            "action": "skip",
            "reason": "Não foram detectados subdomínios neste link, então essa análise não se aplica.",
        },
        {
            "depends_on": "subdomain_count",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "O subdomínio parece aleatório e há muitos subdomínios no mesmo domínio. Esse padrão é muito comum em páginas de phishing hospedadas em plataformas de nuvem.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.2,
            "reason": "O subdomínio parece suspeito, mas o domínio base é muito antigo. Plataformas de nuvem estabelecidas geram subdomínios com aparência aleatória para usuários legítimos.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "O subdomínio parece aleatório, mas o certificado é válido em um domínio estabelecido. Serviços de hospedagem legítimos geram subdomínios assim para seus clientes.",
        },
        {
            "depends_on": "dns_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O subdomínio parece suspeito, mas o DNS está bem configurado. Plataformas de nuvem legítimas costumam ter subdomínios com aparência incomum.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "reduce",
            "factor": 0.5,
            "reason": "O domínio base já foi identificado como aleatório, então analisar o subdomínio separadamente seria contar o mesmo risco duas vezes.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O subdomínio parece aleatório e o domínio é recente. Isso é consistente com uma página de phishing criada recentemente em uma plataforma de nuvem.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.5,
            "reason": "O subdomínio é suspeito e o site pede uma senha. Golpistas hospedam páginas falsas de login em subdomínios aleatórios de plataformas de nuvem para parecer mais legítimo.",
        },
        {
            "depends_on": "random_path_risk",
            "condition": {"op": ">=", "val": 0.4},
            "action": "increase",
            "factor": 1.3,
            "reason": "O subdomínio e o caminho da URL parecem aleatórios. Quando vários componentes do link são suspeitos, aumenta a probabilidade de ser uma URL de phishing gerada automaticamente.",
        },
    ],

    "random_path_risk": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O caminho da URL parece aleatório, mas o site é muito antigo. Sites estabelecidos usam tokens, IDs de sessão e hashes aleatórios legítimos nas URLs.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.3},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O caminho parece aleatório, mas o domínio já existe há algum tempo. Sistemas de gerenciamento de conteúdo e APIs legítimas usam hashes e UUIDs nas URLs.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.35,
            "reason": "O caminho parece aleatório, mas o certificado é válido em um domínio reconhecível. Provavelmente é um ID de recurso ou token de acesso legítimo.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O caminho parece aleatório, mas o domínio é reconhecível. UUIDs e tokens de acesso em URLs de sites conhecidos são normais e seguros.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site é novo e o caminho da URL parece aleatório. URLs descartáveis com caminhos gerados automaticamente são muito comuns em campanhas de phishing.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.2,
            "reason": "O caminho é aleatório e o certificado é inválido. Isso sugere uma URL gerada para entregar conteúdo malicioso em uma infraestrutura sem segurança.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "Tanto o domínio quanto o caminho parecem gerados automaticamente. Quando o link inteiro parece aleatório, é muito provável que tenha sido criado por uma ferramenta automatizada de ataque.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O caminho da URL é aleatório e o site pede uma senha. Páginas de coleta de credenciais costumam usar URLs descartáveis para dificultar o bloqueio.",
        },
    ],

    "query_no_value": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.2,
            "reason": "A URL tem parâmetros vazios, mas o site é muito antigo. Parâmetros sem valor são usados legitimamente em flags de funcionalidade e rastreamento em sites estabelecidos.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "Há parâmetros vazios na URL, mas o certificado é válido. Isso pode ser simplesmente uma forma legítima de ativar funcionalidades específicas.",
        },
        {
            "depends_on": "query_contains_url",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "A URL tem parâmetros vazios e também esconde outro link dentro dela. Essa combinação pode ser usada para redirecionar a vítima de forma disfarçada.",
        },
        {
            "depends_on": "mixed_encoding",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.2,
            "reason": "A URL combina parâmetros vazios com codificação misturada. Isso sugere uma tentativa de esconder o conteúdo real dos parâmetros.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.2,
            "reason": "O site é novo e tem parâmetros vazios na URL. Isso pode indicar uma URL de phishing com estrutura incompleta ou gerada automaticamente.",
        },
    ],

    "query_contains_url": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "Há um link escondido dentro da URL, mas o site é muito antigo. Isso é comum em fluxos de login com OAuth, onde sites estabelecidos precisam redirecionar o usuário.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.15},
            "action": "reduce",
            "factor": 0.25,
            "reason": "A URL contém outro link dentro dela, mas o certificado é completamente válido. Isso pode ser um redirecionamento legítimo como os usados em autenticação OAuth.",
        },
        {
            "depends_on": "mixed_encoding",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "Há um link escondido na URL e a codificação está misturada. Essa combinação é usada para disfarçar o destino final do redirecionamento.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site é novo e tem outro link escondido na URL. Isso é um sinal de redirecionamento aberto — uma técnica usada para levar a vítima a um site malicioso.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.7},
            "action": "increase",
            "factor": 1.3,
            "reason": "Há um link escondido na URL e o certificado é inválido. Redirecionar para um destino sem segurança verificável é muito arriscado.",
        },
        {
            "depends_on": "at_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "A URL tem um link escondido dentro dela e também usa o símbolo '@'. Essas duas técnicas juntas tornam praticamente impossível identificar o destino real do link.",
        },
    ],

    "base64_segment": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "A URL tem dados codificados em base64, mas o site é muito antigo. Tokens de autenticação e dados de sessão codificados assim são completamente normais em sistemas estabelecidos.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "Há base64 na URL, mas o certificado é válido em um domínio estabelecido. Dados codificados em base64 são usados legitimamente para passar informações em URLs.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site é novo e a URL contém dados codificados em base64. Em sites novos, isso pode ser um conteúdo malicioso escondido para evitar detecção.",
        },
        {
            "depends_on": "mixed_encoding",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "A URL combina base64 com outros tipos de codificação. Usar várias camadas de codificação ao mesmo tempo é uma técnica deliberada para esconder conteúdo malicioso.",
        },
        {
            "depends_on": "path_depth_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "A URL tem base64 e também é muito longa e complexa. Esse tipo de URL é construída intencionalmente para ser difícil de analisar por sistemas de segurança.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.2,
            "reason": "A URL tem dados codificados em base64 e o certificado é inválido. Conteúdo escondido em uma infraestrutura sem segurança é um sinal preocupante.",
        },
    ],

    "path_depth_risk": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "A URL tem muitos níveis de caminho, mas o site é muito antigo. Aplicações complexas e CMSs estabelecidos naturalmente criam URLs com muitos níveis.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "A URL é longa e profunda, mas o certificado é válido. APIs e sistemas de gerenciamento de conteúdo legítimos costumam ter URLs com muitos segmentos.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.35,
            "reason": "A URL tem muitos segmentos, mas o domínio é reconhecível. URLs longas são normais em aplicações web legítimas e bem estruturadas.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.2,
            "reason": "O site é novo e a URL tem muitos níveis. Sites descartáveis costumam usar URLs complexas para parecer mais legítimos ou para confundir sistemas de análise.",
        },
        {
            "depends_on": "base64_segment",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "A URL é longa e contém dados codificados em base64. Essa combinação cria uma URL deliberadamente difícil de analisar, o que é suspeito.",
        },
        {
            "depends_on": "random_path_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.2,
            "reason": "A URL tem muitos níveis e os segmentos parecem aleatórios. Isso sugere uma URL construída completamente para escapar de sistemas de detecção.",
        },
    ],

    "fragment_risk": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O fragmento da URL (parte depois do '#') parece suspeito, mas o site é muito antigo. Aplicações modernas de página única (SPA) usam o fragmento para navegação interna de forma legítima.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "O fragmento da URL parece suspeito, mas o certificado é válido. Roteamento via fragmento é uma técnica comum em aplicações web legítimas modernas.",
        },
        {
            "depends_on": "random_path_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O fragmento parece suspeito, mas o caminho da URL em si é normal. Um fragmento isolado é bem menos indicativo de problema do que quando combinado com outros sinais.",
        },
        {
            "depends_on": "xss_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "O fragmento da URL parece suspeito e há padrões de ataque de código. O fragmento pode estar sendo usado para injetar código malicioso na página.",
        },
        {
            "depends_on": "mixed_encoding",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O fragmento da URL é suspeito e a codificação está misturada. Isso pode ser conteúdo malicioso escondido no fragmento usando codificação para disfarçar.",
        },
        {
            "depends_on": "random_path_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.2,
            "reason": "O fragmento e o caminho da URL parecem aleatórios. Quando múltiplas partes do link são suspeitas, a URL foi provavelmente construída inteiramente para evasão.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.2,
            "reason": "O site é novo e o fragmento da URL é suspeito. Links de phishing às vezes usam o fragmento para carregar conteúdo malicioso dinamicamente.",
        },
    ],

    "external_script": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O site carrega scripts de outros domínios, mas é muito antigo. Usar CDNs e bibliotecas externas é uma prática absolutamente normal em sites estabelecidos.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "Há scripts externos, mas o certificado é válido em um domínio estabelecido. Carregar scripts de CDNs como Google ou Cloudflare é prática padrão na web.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O site usa scripts externos, mas o domínio é reconhecível. Analytics e bibliotecas JavaScript de terceiros são comuns em sites legítimos.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site é novo e carrega scripts de outros domínios. Em infraestruturas de ataque recentes, scripts externos podem ser usados para executar código malicioso.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.2,
            "reason": "Há scripts externos e o certificado é inválido. Múltiplos sinais de comprometimento na mesma página aumentam significativamente o risco.",
        },
        {
            "depends_on": "form_action_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "O site carrega scripts externos e envia formulários para outro domínio. Essa combinação é muito usada para coletar e enviar credenciais para servidores de atacantes.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site pede uma senha e carrega scripts de outros domínios. Scripts externos em páginas de login podem ser usados para capturar o que o usuário digita.",
        },
    ],

    "favicon_check": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O ícone do site vem de outro domínio, mas o site é muito antigo. Usar CDNs para servir ícones e imagens é uma prática comum em plataformas estabelecidas.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "O ícone do site é carregado de outro domínio, mas o certificado é válido. CDNs de ícones são usados por sites legítimos para melhorar a performance.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O ícone vem de fora, mas o domínio é reconhecível. Isso é muito comum em plataformas que centralizam recursos visuais em CDNs.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.7},
            "action": "increase",
            "factor": 1.3,
            "reason": "O ícone do site imita uma marca conhecida e o certificado é inválido. Isso é típico de clones de sites legítimos que copiam a identidade visual mas não têm infraestrutura segura.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "O site usa o ícone de outra marca e pede uma senha. Isso é um sinal claro de que o site está se passando por um serviço legítimo para roubar credenciais.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.2,
            "reason": "O site é novo e usa um ícone de outro domínio. Sites de phishing recém-criados frequentemente copiam a identidade visual de marcas conhecidas.",
        },
        {
            "depends_on": "form_action_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site usa o ícone de outra marca e envia formulários para um servidor externo. Isso indica uma clonagem completa de site legítimo para capturar dados.",
        },
    ],

    "image_src_check": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "As imagens vêm de outros domínios, mas o site é muito antigo. CDNs de imagens são usados amplamente por plataformas estabelecidas para melhorar a velocidade.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "As imagens são carregadas de outros domínios, mas o certificado é válido. Usar CDNs para imagens é uma prática padrão de performance na web.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.35,
            "reason": "As imagens vêm de fora, mas o domínio é reconhecível. CDNs de imagens são comuns e legítimos em sites bem-estruturados.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.2,
            "reason": "O site é novo e carrega imagens de outros domínios. Sites de phishing frequentemente copiam imagens diretamente do site legítimo que estão imitando.",
        },
        {
            "depends_on": "form_action_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site carrega imagens externas e envia formulários para outro domínio. Isso sugere uma clonagem do site legítimo para enganar a vítima.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.2,
            "reason": "O site usa imagens de outra marca e pede uma senha. Isso é um padrão de clone de página de login para roubo de credenciais.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.15,
            "reason": "As imagens vêm de outros domínios e o certificado é inválido. Um clone de site em uma infraestrutura sem segurança é especialmente perigoso.",
        },
    ],

    "redirect_check": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O site redireciona para outro endereço, mas é muito antigo. Redirecionamentos são absolutamente normais em sites estabelecidos para reorganizar conteúdo ou mover páginas.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "Há um redirecionamento, mas o certificado é válido. Redirecionar de HTTP para HTTPS é uma prática de segurança padrão em sites legítimos.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.3},
            "action": "reduce",
            "factor": 0.5,
            "reason": "O site redireciona, mas o domínio não parece aleatório. Redirecionamentos em domínios reconhecíveis geralmente têm propósito legítimo.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site é novo e redireciona para outro endereço. Sites maliciosos recentes usam redirecionamentos para esconder o destino final e escapar de bloqueios.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.2,
            "reason": "O site redireciona e o certificado é inválido. Redirecionar sem segurança adequada em uma infraestrutura comprometida é muito preocupante.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "O site pede uma senha e redireciona para outro endereço. Isso pode ser uma técnica para coletar credenciais antes de enviar a vítima para o site real, fazendo o ataque parecer imperceptível.",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.2,
            "reason": "O site tem subdomínio suspeito e redireciona para outro endereço. Golpistas usam subdomínios de plataformas de nuvem combinados com redirecionamentos para dificultar o bloqueio.",
        },
    ],

    "hidden_fields_check": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O formulário tem campos ocultos, mas o site é muito antigo. Tokens de proteção contra ataques (CSRF) e dados de sessão em campos ocultos são uma prática de segurança legítima.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "Há campos ocultos no formulário, mas o certificado é válido. Campos ocultos para rastreamento e controle de fluxo são comuns em sites legítimos.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.35,
            "reason": "O formulário tem campos ocultos, mas o domínio é reconhecível. Campos ocultos em sites conhecidos geralmente têm função técnica legítima.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O formulário tem campos ocultos e o certificado é inválido. Dados sendo coletados sem proteção de segurança é uma situação de risco.",
        },
        {
            "depends_on": "form_action_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "O formulário tem campos ocultos e envia os dados para outro domínio. Campos ocultos podem estar coletando dados adicionais do usuário sem que ele saiba.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O formulário tem campos ocultos e pede uma senha. Isso configura um formulário completo de coleta de credenciais, muito comum em páginas de phishing.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.2,
            "reason": "O site é novo e tem campos ocultos no formulário. Em uma infraestrutura descartável, campos ocultos provavelmente coletam dados para enviar a um atacante.",
        },
    ],

    "password_input_check": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.05},
            "action": "reduce",
            "factor": 0.1,
            "reason": "O site pede uma senha, mas existe há muitos anos. Páginas de login em sites muito estabelecidos são completamente normais e esperadas.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "Há um campo de senha, mas o site já é estabelecido. Logins em sites com histórico sólido são legítimos.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O site pede uma senha e o certificado de segurança está completamente válido. Uma página de login com segurança adequada é o comportamento esperado.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "O site pede uma senha, mas o domínio é reconhecível. Logins em serviços conhecidos são legítimos.",
        },
        {
            "depends_on": "form_action_check",
            "condition": {"op": "is_none"},
            "action": "reduce",
            "factor": 0.85,
            "reason": "O formulário não envia dados para um servidor externo, o que torna o campo de senha menos preocupante. O site parece processar o login internamente.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.4,
            "reason": "O site pede uma senha, mas não tem certificado de segurança válido. Nunca é seguro digitar senhas em sites sem conexão segura (HTTPS).",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.4,
            "reason": "Um site recém-criado está pedindo uma senha. Sites legítimos raramente pedem credenciais logo após o lançamento sem nenhum histórico.",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.5,
            "reason": "O site tem subdomínio suspeito e pede uma senha. Golpistas hospedam páginas falsas de login em subdomínios de plataformas conhecidas para parecer mais legítimos.",
        },
        {
            "depends_on": "ip_in_url",
            "condition": {"op": ">=", "val": 0.7},
            "action": "increase",
            "factor": 1.5,
            "reason": "O site pede uma senha e o endereço é um número de IP, não um domínio. Inserir senhas em servidores identificados apenas por IP é extremamente arriscado.",
        },
    ],

    "form_action_check": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.2,
            "reason": "O formulário envia dados para outro domínio, mas o site é muito antigo. Integrações com sistemas de pagamento e CRMs externos são práticas legítimas em sites estabelecidos.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "O formulário envia para um servidor externo, mas o certificado é válido. Integração com serviços externos como processadores de pagamento é comum e legítima.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.35,
            "reason": "O formulário envia dados para fora, mas o domínio é reconhecível. Integrações com serviços externos são normais em sites de empresas conhecidas.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": "is_none"},
            "action": "reduce",
            "factor": 0.5,
            "reason": "O formulário envia para um servidor externo, mas não pede senha. Sem credenciais em jogo, o risco é menor, podendo ser apenas um formulário de contato.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.5,
            "reason": "O formulário envia dados para outro servidor e o certificado é inválido. Dados sendo enviados sem proteção de segurança é uma situação de alto risco.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.5,
            "reason": "O site é novo e envia os dados do formulário para outro servidor. Isso é um dos sinais mais claros de uma página de phishing — coletar dados e enviar para o atacante.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.5,
            "reason": "O formulário pede uma senha e envia os dados para um servidor externo. Essa é a combinação mais perigosa: credenciais sendo coletadas e enviadas para terceiros.",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "O formulário envia dados para fora e o subdomínio é suspeito. Isso sugere uma página falsa hospedada em plataforma de nuvem coletando dados dos visitantes.",
        },
        {
            "depends_on": "ip_in_url",
            "condition": {"op": ">=", "val": 0.7},
            "action": "increase",
            "factor": 1.4,
            "reason": "O formulário envia dados para um servidor identificado apenas por número de IP. Enviar informações pessoais para um servidor sem nome verificável é muito arriscado.",
        },
    ],

    "safe_browsing": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.05,
            "reason": "O site foi sinalizado pelo Google Safe Browsing, mas existe há muitos anos. Domínios muito antigos às vezes são marcados por erros históricos que já foram resolvidos.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.2,
            "reason": "O site foi sinalizado pelo Google Safe Browsing, mas o certificado está completamente válido. Pode ser um falso positivo, já que o Google às vezes marca sites legítimos incorretamente.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O Google Safe Browsing sinalizou este site e o nome do domínio parece aleatório. Esses dois fatores juntos confirmam que provavelmente é uma infraestrutura maliciosa.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.4,
            "reason": "O site foi bloqueado pelo Google Safe Browsing e é recente. Isso indica uma campanha maliciosa ativa que o Google já identificou e está bloqueando.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.5,
            "reason": "O Google Safe Browsing bloqueou este site e ele pede uma senha. O Google confirmou que este site é perigoso e está tentando coletar credenciais.",
        },
        {
            "depends_on": "dns_score",
            "condition": {"op": ">=", "val": 0.7},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site foi sinalizado pelo Google e tem infraestrutura DNS suspeita. Esses dois fatores juntos confirmam uma infraestrutura maliciosa completa.",
        },
    ],

    "client_hints_collection": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.1,
            "reason": "O site coleta informações técnicas do navegador, mas é muito antigo. Plataformas estabelecidas coletam esses dados legitimamente para otimizar a experiência do usuário.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.3},
            "action": "reduce",
            "factor": 0.35,
            "reason": "O site coleta dados técnicos do navegador, mas já está estabelecido. Coletar métricas de dispositivo para analytics é uma prática comum em serviços legítimos.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.4,
            "reason": "O site coleta dados do navegador, mas o certificado é válido. Analytics legítimos coletam esse tipo de dado de forma transparente.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site é novo e já está coletando informações técnicas detalhadas do navegador. Sites criados às pressas para golpes não costumam ter interesse em analytics legítimos.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "O site pede uma senha e coleta dados técnicos do navegador. Combinar coleta de credenciais com fingerprinting do dispositivo é uma técnica usada por golpistas sofisticados.",
        },
        {
            "depends_on": "safe_browsing",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O Google Safe Browsing sinalizou este site e ele ainda está coletando dados do navegador. Um site malicioso confirmado que realiza fingerprinting é especialmente perigoso.",
        },
    ],

    "inline_data_uri": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O site usa recursos embutidos diretamente no código (data URIs), mas é muito antigo. Incorporar imagens e ícones diretamente no HTML é uma técnica de otimização legítima.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "Há recursos embutidos no código, mas o certificado é válido. Embutir recursos para melhorar a performance é uma prática de desenvolvimento web comum e legítima.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.35,
            "reason": "O site usa recursos embutidos, mas o domínio é reconhecível. Bundling de recursos em sites legítimos é uma escolha técnica normal.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site é novo e embute recursos diretamente no código. Sites de phishing fazem isso para não precisar de requisições externas que seriam mais facilmente detectadas.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site pede uma senha e usa recursos embutidos. Clonar uma página de login e embutir todos os recursos é uma técnica para criar phishing que funciona mesmo offline.",
        },
        {
            "depends_on": "safe_browsing",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "O Google Safe Browsing sinalizou este site e ele usa recursos embutidos no código. Esconder recursos em um site já confirmado como malicioso indica intenção de evasão.",
        },
        {
            "depends_on": "form_action_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.2,
            "reason": "O site usa recursos embutidos e envia formulários para outro servidor. Isso configura um clone completo de site legítimo com todos os elementos necessários para enganar a vítima.",
        },
    ],

    "missing_form_tag": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "O site coleta dados sem usar um formulário tradicional, mas é muito antigo. Aplicações modernas de página única (SPA) frequentemente usam JavaScript para enviar dados sem formulários convencionais.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "Há coleta de dados sem formulário tradicional, mas o certificado é válido. Aplicações modernas usam fetch e outras APIs JavaScript para enviar dados, o que é legítimo.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.35,
            "reason": "O site coleta dados sem formulário convencional, mas o domínio é reconhecível. SPAs e aplicações modernas legítimas costumam usar essa abordagem.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.4,
            "reason": "O site é novo e captura dados via JavaScript sem usar formulários tradicionais. Essa técnica é usada em phishing avançado para capturar credenciais de forma menos detectável.",
        },
        {
            "depends_on": "safe_browsing",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.5,
            "reason": "O Google Safe Browsing bloqueou este site e ele captura dados sem formulário. Um site confirmado como malicioso usando técnicas avançadas de coleta de dados é muito perigoso.",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site tem subdomínio suspeito e captura dados sem formulário convencional. Isso sugere uma página de phishing sofisticada hospedada em plataforma de nuvem.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site captura dados sem formulário e o certificado é inválido. Coletar informações sem segurança adequada e sem transparência é um sinal muito preocupante.",
        },
    ],

    "script_integrity_absent": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.15,
            "reason": "Os scripts externos não têm verificação de integridade, mas o site é muito antigo. A maioria dos sites legítimos não configura essa verificação, então a ausência não é necessariamente suspeita.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "Scripts sem verificação de integridade, mas o certificado é válido. Não usar verificação de integridade em scripts de CDN é comum mesmo em sites legítimos bem estabelecidos.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.35,
            "reason": "Scripts sem verificação de integridade, mas o domínio é reconhecível. A ausência de SRI é tão comum na web que por si só não indica problema.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.3,
            "reason": "O site é novo e os scripts externos não têm verificação de integridade. Em infraestruturas de ataque, isso pode indicar que os scripts foram substituídos por versões maliciosas.",
        },
        {
            "depends_on": "safe_browsing",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "O Google Safe Browsing sinalizou este site e os scripts não têm verificação de integridade. Num site já confirmado como malicioso, scripts não verificáveis são especialmente perigosos.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "O site pede uma senha e os scripts externos não têm verificação. Scripts não verificados em páginas de login podem capturar tudo que o usuário digita.",
        },
        {
            "depends_on": "form_action_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.3,
            "reason": "O formulário envia dados para fora e os scripts não têm verificação. Scripts não verificados podem interceptar os dados antes mesmo de serem enviados.",
        },
    ],

    "typosquatting": [
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.1},
            "action": "reduce",
            "factor": 0.1,
            "reason": "O nome do domínio é parecido com o de uma marca conhecida, mas o site é muito antigo. Marcas consolidadas às vezes têm nomes muito próximos a outras marcas legítimas.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": "<", "val": 0.3},
            "action": "reduce",
            "factor": 0.3,
            "reason": "O domínio se parece com o de uma marca conhecida, mas já está no ar há algum tempo. Pode ser uma empresa legítima com nome similar por coincidência ou pela mesma área de atuação.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": "<", "val": 0.15},
            "action": "reduce",
            "factor": 0.25,
            "reason": "O domínio lembra o de uma marca conhecida, mas tem certificado completamente válido. Marcas legítimas com nomes similares investem em segurança adequada.",
        },
        {
            "depends_on": "dns_score",
            "condition": {"op": "<", "val": 0.2},
            "action": "reduce",
            "factor": 0.3,
            "reason": "O nome é parecido com uma marca conhecida, mas o DNS está saudável e tem e-mail configurado. Empresas legítimas com nomes similares têm infraestrutura completa.",
        },
        {
            "depends_on": "domain_age",
            "condition": {"op": ">", "val": 0.8},
            "action": "increase",
            "factor": 1.5,
            "reason": "O domínio imita o nome de uma marca conhecida e foi registrado recentemente. Registrar domínios parecidos com marcas famosas é uma das técnicas mais comuns de phishing.",
        },
        {
            "depends_on": "ssl_score",
            "condition": {"op": ">=", "val": 0.7},
            "action": "increase",
            "factor": 1.3,
            "reason": "O domínio imita uma marca e o certificado é inválido. Um site que tenta passar por uma marca mas não tem segurança adequada é suspeito.",
        },
        {
            "depends_on": "dns_score",
            "condition": {"op": ">=", "val": 0.7},
            "action": "increase",
            "factor": 1.3,
            "reason": "O domínio imita uma marca e o DNS está mal configurado. Uma infraestrutura mínima num domínio que imita marca conhecida é um sinal forte de golpe.",
        },
        {
            "depends_on": "password_input_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.6,
            "reason": "O site imita o nome de uma marca conhecida e pede uma senha. Essa é a essência do phishing: enganar a vítima com um nome familiar para roubar suas credenciais.",
        },
        {
            "depends_on": "form_action_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.5,
            "reason": "O domínio imita uma marca e envia formulários para outro servidor. Isso confirma que o site está se passando por uma empresa conhecida para capturar dados dos usuários.",
        },
        {
            "depends_on": "safe_browsing",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.5,
            "reason": "O Google Safe Browsing confirmou que este site que imita uma marca é malicioso. Essa é uma confirmação direta de que se trata de um golpe de phishing.",
        },
        {
            "depends_on": "favicon_check",
            "condition": {"op": ">=", "val": 0.5},
            "action": "increase",
            "factor": 1.4,
            "reason": "O domínio imita uma marca e usa o ícone dela. Copiar tanto o nome quanto a identidade visual de uma empresa é uma tentativa clara de enganar os usuários.",
        },
        {
            "depends_on": "rdap_metadata_incompleteness",
            "condition": {"op": ">=", "val": 0.6},
            "action": "increase",
            "factor": 1.3,
            "reason": "O domínio imita uma marca e as informações de registro estão ocultas. Quem registra um domínio falso esconde a identidade para não ser responsabilizado.",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": {"op": ">=", "val": 0.5},
            "action": "reduce",
            "factor": 0.5,
            "reason": "O domínio foi sinalizado como aleatório, o que contradiz a hipótese de typosquatting intencional. Um nome completamente aleatório não imita uma marca específica de propósito.",
        },
    ],
}