DEPENDENCIES: dict[str, list[dict]] = {
    "ssl_verify": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.15,
            "action": "reduce",
            "factor": 0.15,
            "reason": "domínio estabelecido — certificado recente é renovação normal",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.05,
            "action": "reduce",
            "factor": 0.05,
            "reason": "domínio muito antigo com SSL moderado — infraestrutura consolidada",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.5,
            "reason": "SSL suspeito + domínio novo — combinação de alto risco",
        },
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.4,
            "reason": "SSL moderado + DNS saudável — infraestrutura estabelecida",
        },
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "SSL moderado + DNS completamente saudável — provável falso positivo de CDN",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "SSL suspeito mas domínio reconhecível — provável renovação ou misconfiguration pontual",
        },
    ],
    "domain_age": [
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is None,
            "action": "skip",
            "reason": "DNS falhou — domain age pode ser impreciso",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "domínio novo + SSL inválido — infraestrutura de phishing típica",
        },
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "domínio novo + DNS suspeito — confirma infraestrutura descartável",
        },
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.5,
            "reason": "domínio novo mas DNS saudável — pode ser site legítimo recém-lançado",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "domínio novo mas SSL válido de CA estabelecida — provável serviço legítimo recém-lançado",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "domínio novo mas nome reconhecível — produto ou serviço recém-lançado",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "domínio novo + subdomínio suspeito — phishing em plataforma cloud recém-criado",
        },
    ],
    "dns_verify": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.5,  
            "reason": "DNS suspeito mas domínio muito antigo — provavelmente CDN ou balanceamento legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.75,  
            "reason": "DNS suspeito mas domínio estabelecido — configuração não convencional mas legítima",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "DNS sem MX mas SSL válido — provável landing page ou site estático legítimo",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "DNS sem MX + SSL completamente válido — site estático legítimo sem email próprio",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "DNS suspeito mas domínio reconhecível — infraestrutura não convencional de serviço legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "DNS suspeito + domínio novo — padrão de infraestrutura descartável",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.9,
            "action": "increase",
            "factor": 1.4,
            "reason": "DNS suspeito + SSL completamente inválido — infraestrutura completamente suspeita",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "DNS suspeito + SSL inválido — múltiplos sinais de infraestrutura maliciosa",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.6,
            "action": "increase",
            "factor": 1.3,
            "reason": "DNS suspeito + domínio aleatório — possível domínio DGA",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "DNS sem MX + subdomínio suspeito — infraestrutura de phishing em plataforma cloud",
        },
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "DNS suspeito + path suspeito — servidor malicioso com URL estruturada para evasão",
        },
    ],
    "random_domain_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.1,
            "reason": "domínio com alta entropia mas idade estabelecida — provável marca legítima",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.05,
            "action": "reduce",
            "factor": 0.05,
            "reason": "domínio muito antigo com entropia alta — marca consolidada ou sigla",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "entropia alta mas certificado de CA estabelecida — provável serviço legítimo",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "entropia alta mas certificado EV ou wildcard de grande CA — serviço legítimo consolidado",
        },
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "entropia alta mas DNS saudável com MX — empresa legítima com nome incomum",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "domínio aleatório + recém-criado — padrão DGA ou geração automática",
        },
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "domínio aleatório + infraestrutura DNS mínima — descartável",
        },
    ],
    "random_subdomain_risk": [
        {
            "depends_on": "subdomain_count",
            "condition": lambda v: v is None,
            "action": "skip",
            "reason": "sem subdomínios detectados",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "reduce",
            "factor": 0.5,
            "reason": "domínio base já sinalizado como aleatório — sinal redundante",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "subdomínio suspeito mas SSL válido em domínio estabelecido — plataforma de hosting legítima",
        },  
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "subdomínio suspeito mas DNS saudável — plataforma cloud legítima",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "subdomínio suspeito + domínio novo — phishing em plataforma",
        },
        {
            "depends_on": "subdomain_count",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "subdomínio suspeito + estrutura de múltiplos níveis — padrão de phishing em cloud storage",
        },
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is not None and v >= 0.4,
            "action": "increase",
            "factor": 1.3,
            "reason": "subdomínio suspeito + path suspeito — URL de phishing estruturada em plataforma",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is not None and v >= 1.0,
            "action": "increase",
            "factor": 1.6,
            "reason": "subdomínio suspeito + campo de senha — credential harvesting confirmado em plataforma cloud",
        },
    ],
    "subdomain_count": [
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "múltiplos subdomínios em domínio base reconhecido — estrutura de plataforma cloud legítima",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.3,
            "reason": "múltiplos subdomínios em domínio muito antigo — plataforma cloud estabelecida",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "múltiplos subdomínios com SSL válido — plataforma cloud legítima com wildcard cert",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "muitos subdomínios + subdomínio suspeito — padrão de hosting em cloud com nome gerado",
        },
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is not None and v >= 0.6,
            "action": "increase",
            "factor": 1.2,
            "reason": "múltiplos subdomínios + DNS sem MX — padrão de site descartável em cloud",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "múltiplos subdomínios + SSL inválido — cloud storage phishing sem configuração adequada",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "múltiplos subdomínios + domínio novo — infraestrutura descartável em cloud",
        },
    ],
    "hyphen_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "hífens em domínio muito antigo — nome legítimo consolidado",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.4,
            "reason": "hífens em domínio estabelecido — nome descritivo legítimo",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "hífens mas SSL válido de CA estabelecida — domínio descritivo legítimo",
        },
        {
            "depends_on": "num_ratio_risk",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.6,
            "reason": "sem números no domínio, hífens isolados são menos suspeitos",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "hífens em domínio com baixa entropia — nome descritivo intencional",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "hífens + domínio novo — padrão de domínio gerado automaticamente",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "hífens + entropia alta no domínio — padrão de geração automática confirmado",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "hífens + SSL inválido — domínio descartável sem infraestrutura adequada",
        },
    ],
    "num_ratio_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "números no domínio mas domínio muito antigo — nome legítimo estabelecido",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.4,
            "reason": "números em domínio estabelecido — nome legítimo com identificador numérico",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "números no domínio mas SSL válido — serviço legítimo com nome numérico",
        },
        {
            "depends_on": "hyphen_risk",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.6,
            "reason": "sem hífens, proporção de números isolada é menos indicativa de DGA",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "números mas entropia baixa — domínio estruturado intencionalmente",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "números + domínio novo — padrão de geração automática de domínio",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "números + entropia alta — domínio com perfil DGA",
        },
        {
            "depends_on": "hyphen_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "números + hífens — combinação típica de domínio gerado automaticamente",
        },
    ],
    "random_path_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "path aleatório em domínio muito antigo — token ou ID de sessão legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.4,
            "reason": "path aleatório em domínio estabelecido — provável hash de conteúdo ou UUID legítimo",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "path aleatório mas SSL válido em domínio reconhecível — ID de recurso legítimo",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "path aleatório em domínio reconhecível — UUID ou token de acesso legítimo",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "path aleatório + domínio aleatório — URL inteiramente gerada automaticamente",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "path aleatório + domínio novo — URL descartável típica de campanha de phishing",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "path aleatório + SSL inválido — infraestrutura de entrega de payload",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "path aleatório + subdomínio aleatório — URL completamente gerada em plataforma cloud",
        },
    ],
    "external_script": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "scripts externos em domínio muito antigo — CDN ou biblioteca legítima",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "scripts externos mas SSL válido em domínio estabelecido — integração legítima com CDN",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "scripts externos em domínio reconhecível — uso de CDN ou analytics legítimo",
        },
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is not None and v >= 1.0,
            "action": "increase",
            "factor": 1.4,
            "reason": "scripts externos + form action externo — credential harvesting provável",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "scripts externos + domínio novo — infraestrutura de ataque recente",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "scripts externos + SSL inválido — múltiplos sinais de comprometimento",
        },
    ],
    "form_action_check": [
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "form action externo mas SSL válido em domínio estabelecido — integração legítima",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.3,
            "reason": "form action externo em domínio muito antigo — integração com serviço de pagamento ou CRM",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.5,
            "reason": "sem campo de senha, form action externo é menos crítico",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.5,
            "reason": "form action externo + domínio novo — coleta de credenciais em site descartável",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "form action externo + subdomínio suspeito — coleta de dados em plataforma cloud",
        },
    ],
    "password_input_check": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.05,
            "action": "reduce",
            "factor": 0.1,
            "reason": "campo de senha em domínio muito estabelecido — página de login legítima",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "campo de senha em domínio estabelecido — login legítimo",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "campo de senha com SSL completamente válido — página de login segura",
        },
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.6,
            "reason": "sem form action externo, campo de senha é menos crítico",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "campo de senha em domínio reconhecível — login de serviço legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "campo de senha + domínio novo — credential harvesting em site descartável",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "campo de senha + SSL inválido — coleta de credenciais sem proteção",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.5,
            "reason": "campo de senha + subdomínio suspeito — credential harvesting em plataforma legítima",
        },
    ],
    "hidden_fields_check": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "campos ocultos em domínio muito antigo — tokens CSRF ou dados de sessão legítimos",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "campos ocultos mas SSL válido em domínio estabelecido — campos de rastreamento legítimos",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.4,
            "reason": "sem campo de senha, campos ocultos são menos suspeitos",
        },
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is not None and v >= 1.0,
            "action": "increase",
            "factor": 1.4,
            "reason": "campos ocultos + form action externo — exfiltração de dados provável",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "campos ocultos + SSL inválido — exfiltração de dados sem proteção",
        },
    ],
    "favicon_check": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "favicon externo em domínio muito antigo — CDN ou serviço de ícones legítimo",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "favicon externo mas SSL válido — uso de CDN de ícones legítimo",
        },
        {
            "depends_on": "external_script",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.4,
            "reason": "sem scripts externos, favicon externo tem baixo valor diagnóstico isolado",
        },
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.4,
            "reason": "sem form action externo, favicon externo é menos relevante",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is not None and v >= 1.0,
            "action": "increase",
            "factor": 1.4,
            "reason": "favicon externo + campo de senha — possível clone de site legítimo para coleta",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "favicon externo + domínio novo — clone de identidade visual em infraestrutura recente",
        },
    ],
    "image_src_check": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "imagens externas em domínio muito antigo — uso legítimo de CDN de imagens",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "imagens externas mas SSL válido em domínio estabelecido — CDN legítimo",
        },
        {
            "depends_on": "external_script",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.35,
            "reason": "sem scripts externos, imagens externas têm baixo valor diagnóstico isolado",
        },
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is not None and v >= 1.0,
            "action": "increase",
            "factor": 1.3,
            "reason": "imagens externas + form action externo — clonagem de site legítimo provável",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "imagens externas + domínio novo — possível clone de site legítimo",
        },
    ],
    "redirect_check": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "redirect em domínio muito antigo — redirecionamento estrutural legítimo",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "redirect mas SSL válido em domínio estabelecido — redirect HTTP→HTTPS legítimo",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is None or v < 0.3,
            "action": "reduce",
            "factor": 0.5,
            "reason": "domínio não aleatório com redirect — redirecionamento estrutural legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "redirect externo + domínio novo — evasão de detecção provável",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "redirect externo + SSL inválido — evasão com infraestrutura comprometida",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "redirect externo + subdomínio suspeito — evasão via plataforma cloud",
        },
    ],
    "query_contains_url": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "URL na query em domínio muito antigo — parâmetro de redirect legítimo",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "URL na query mas SSL válido em domínio estabelecido — OAuth ou redirect legítimo",
        },
        {
            "depends_on": "query_no_value",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.5,
            "reason": "sem parâmetros vazios, URL na query é menos suspeita",
        },
        {
            "depends_on": "mix_encoding",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "URL na query + encoding misto — obfuscação intencional de destino",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "URL na query + domínio novo — possível open redirect em infraestrutura descartável",
        },
    ],
    "base64_segment": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "base64 em domínio muito antigo — token de autenticação ou ID de recurso legítimo",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "base64 mas SSL válido em domínio estabelecido — dado codificado legítimo na URL",
        },
        {
            "depends_on": "mix_encoding",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.5,
            "reason": "sem encoding misto, base64 isolado é menos indicativo",
        },
        {
            "depends_on": "path_depth_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "base64 + path profundo — obfuscação estruturada de URL",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "base64 na URL + domínio novo — possível entrega de payload ofuscado",
        },
    ],
    "xss_pattern": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "padrão XSS em domínio muito antigo — possível falso positivo em campo de busca legítimo",
        },
        {
            "depends_on": "mix_encoding",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.6,
            "reason": "sem encoding misto, padrão XSS tem menor chance de ser exploração real",
        },
        {
            "depends_on": "query_contains_url",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "padrão XSS + URL na query — possível ataque de redirecionamento com payload",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "padrão XSS + domínio novo — infraestrutura de ataque recém-criada",
        },
    ],
    "path_depth_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "path profundo em domínio muito antigo — estrutura de rotas de aplicação legítima",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "path profundo mas SSL válido em domínio estabelecido — rotas de API ou CMS legítimo",
        },
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.4,
            "reason": "sem segmentos aleatórios, profundidade sozinha é menos relevante",
        },
        {
            "depends_on": "base64_segment",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "path profundo + base64 — estrutura de URL obfuscada",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "path profundo + domínio novo — URL complexa em infraestrutura descartável",
        },
    ],
    "fragment_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "fragmento suspeito em domínio muito antigo — SPA com roteamento via hash",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "fragmento suspeito mas SSL válido em domínio estabelecido — roteamento de SPA legítimo",
        },
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.4,
            "reason": "sem path aleatório, fragmento isolado é menos indicativo",
        },
        {
            "depends_on": "xss_pattern",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "fragmento suspeito + padrão XSS — possível injeção via hash da URL",
        },
        {
            "depends_on": "mix_encoding",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "fragmento suspeito + encoding misto — obfuscação de payload no hash",
        },
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "fragmento suspeito + path aleatório — URL de payload completamente ofuscada",
        },
    ],
    "query_no_value": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "parâmetros vazios em domínio muito antigo — parâmetros opcionais de tracking legítimo",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "parâmetros vazios mas SSL válido em domínio estabelecido — parâmetros de feature flag legítimos",
        },
        {
            "depends_on": "query_contains_url",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "parâmetros vazios + URL na query — estrutura de open redirect com evasão",
        },
        {
            "depends_on": "mix_encoding",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "parâmetros vazios + encoding misto — obfuscação de parâmetros",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "parâmetros vazios + domínio novo — URL de phishing com estrutura incompleta",
        },
    ],
}