DEPENDENCIES: dict[str, list[dict]] = {
    "ssl_verify": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.15,
            "action": "reduce",
            "factor": 0.2,
            "reason": "domínio estabelecido — certificado recente é renovação normal",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.5,
            "reason": "SSL suspeito + domínio novo — combinação de alto risco",
        },
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.6,
            "reason": "SSL moderado + DNS saudável — infraestrutura estabelecida",
        },
    ],
    "domain_age": [
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is None,
            "action": "skip",
            "reason": "DNS falhou, domain age pode ser impreciso",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "domínio novo + SSL inválido — infraestrutura de phishing típica",
        },
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "domínio novo + DNS suspeito — confirma infraestrutura descartável",
        },
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.7,
            "reason": "domínio novo mas DNS saudável — pode ser site legítimo recém-lançado",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "domínio novo + subdomínio suspeito — phishing em plataforma cloud recém-criado",
        },
    ],
    "dns_verify": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "DNS suspeito + domínio novo — padrão de infraestrutura descartável",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "DNS suspeito + SSL inválido — múltiplos sinais de infraestrutura maliciosa",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.4,
            "reason": "DNS suspeito mas domínio muito antigo — provavelmente CDN ou balanceamento legítimo",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.5,
            "reason": "DNS sem MX mas SSL válido — provável landing page ou site estático legítimo",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.9,
            "action": "increase",
            "factor": 1.4,
            "reason": "DNS suspeito + SSL completamente inválido — infraestrutura completamente suspeita",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.6,
            "action": "increase",
            "factor": 1.3,
            "reason": "DNS suspeito + domínio aleatório — possível domínio DGA",
        },
        {
            "depends_on": "subdomain_count",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "DNS sem MX + múltiplos subdomínios — site descartável em cloud storage",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "DNS sem MX + subdomínio suspeito — infraestrutura de phishing em plataforma cloud",
        },
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "DNS suspeito + path suspeito — servidor malicioso com URL estruturada para evasão",
        },
    ],
    "random_domain_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.1,
            "reason": "domínio com alta entropia mas idade estabelecida — provável marca legítima",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "domínio aleatório + recém-criado — padrão DGA ou geração automática",
        },
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "domínio aleatório + infraestrutura DNS mínima — descartável",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.5,
            "reason": "domínio com entropia alta mas certificado de CA estabelecida — provável serviço legítimo",
        },
    ],
    "random_subdomain_risk": [
        {
            "depends_on": "subdomain_count",
            "condition": lambda v: v is None,
            "action": "skip",
            "reason": "sem subdomínios detectados",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "reduce",
            "factor": 0.5,
            "reason": "domínio base já sinalizado como aleatório",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "subdomínio suspeito + domínio novo — phishing em plataforma",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "subdomínio suspeito mas SSL válido em domínio estabelecido — plataforma de hosting legítima",
        },
        {
            "depends_on": "subdomain_count",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "subdomínio suspeito + estrutura de múltiplos níveis — padrão de phishing em cloud storage",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "subdomínio suspeito em plataforma cloud com SSL compartilhado — phishing em infraestrutura legítima",
        },
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is not None and v >= 0.4,
            "action": "increase",
            "factor": 1.3,
            "reason": "subdomínio suspeito + path suspeito — URL de phishing estruturada em plataforma",
        },
    ],
    "subdomain_count": [
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "muitos subdomínios + subdomínio suspeito — padrão de hosting em cloud com nome gerado",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.5,
            "reason": "múltiplos subdomínios em domínio base reconhecido — estrutura de plataforma cloud legítima",
        },
        {
            "depends_on": "dns_verify",
            "condition": lambda v: v is not None and v >= 0.6,
            "action": "increase",
            "factor": 1.2,
            "reason": "múltiplos subdomínios + DNS sem MX — padrão de site descartável em cloud",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "múltiplos subdomínios + SSL inválido — cloud storage phishing sem configuração adequada",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "múltiplos subdomínios + domínio novo — infraestrutura descartável em cloud",
        },
    ],
    "external_script": [
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is not None and v >= 1.0,
            "action": "increase",
            "factor": 1.4,
            "reason": "form action externo + scripts suspeitos — credential harvesting provável",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "scripts suspeitos + domínio novo — infraestrutura de ataque recente",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "scripts suspeitos + SSL inválido — múltiplos sinais de comprometimento",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.6,
            "reason": "script externo em domínio muito antigo — possível comprometimento pontual, não phishing estruturado",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "scripts suspeitos + subdomínio aleatório — ataque estruturado em plataforma cloud",
        },
    ],
    "form_action_check": [
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.5,
            "reason": "sem campo de senha, form action externo é menos crítico",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.5,
            "reason": "form action externo + domínio novo — coleta de credenciais em site descartável",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "form action externo mas SSL válido em domínio estabelecido — provável integração legítima",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "form action externo + subdomínio suspeito — coleta de dados em plataforma cloud",
        },
    ],
    "password_input_check": [
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.7,
            "reason": "sem form action externo, campo de senha é menos crítico",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "campo de senha + domínio novo — credential harvesting em site descartável",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "campo de senha + SSL inválido — coleta de credenciais sem proteção",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.5,
            "reason": "campo de senha + subdomínio suspeito — credential harvesting em plataforma legítima",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.05,
            "action": "reduce",
            "factor": 0.2,
            "reason": "campo de senha em domínio muito estabelecido — página de login legítima",
        },
    ],
    "hidden_fields_check": [
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.5,
            "reason": "sem campo de senha, campos ocultos são menos suspeitos",
        },
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is not None and v >= 1.0,
            "action": "increase",
            "factor": 1.4,
            "reason": "campos ocultos + form action externo — exfiltração de dados provável",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "campos ocultos + SSL inválido — exfiltração de dados sem proteção",
        },
    ],
    "num_ratio_risk": [
        {
            "depends_on": "hyphen_risk",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.7,
            "reason": "sem hífens, proporção de números é menos indicativa de DGA",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "números + domínio novo — padrão de geração automática de domínio",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.3,
            "reason": "números no domínio mas domínio muito antigo — nome legítimo estabelecido",
        },
    ],
    "hyphen_risk": [
        {
            "depends_on": "num_ratio_risk",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.7,
            "reason": "sem números no domínio, hífens são menos suspeitos",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "hífens + domínio novo — padrão de domínio gerado automaticamente",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.3,
            "reason": "hífens em domínio muito antigo — nome legítimo estabelecido",
        },
    ],
    "redirect_check": [
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is None or v < 0.4,
            "action": "reduce",
            "factor": 0.6,
            "reason": "domínio não sinalizado como aleatório, redirect é menos suspeito",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "redirect externo + domínio novo — evasão de detecção provável",
        },
        {
            "depends_on": "ssl_verify",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "redirect externo + SSL inválido — evasão com infraestrutura comprometida",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "redirect externo + subdomínio suspeito — evasão via plataforma cloud",
        },
    ],
    "query_contains_url": [
        {
            "depends_on": "query_no_value",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.6,
            "reason": "nenhum parâmetro vazio detectado, URL na query é menos suspeita",
        },
        {
            "depends_on": "mix_encoding",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "URL na query + encoding misto — obfuscação intencional de destino",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "URL na query + domínio novo — possível open redirect em infraestrutura descartável",
        },
    ],
    "base64_segment": [
        {
            "depends_on": "mix_encoding",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.6,
            "reason": "sem encoding misto, base64 isolado é menos indicativo",
        },
        {
            "depends_on": "path_depth_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "base64 + path profundo — obfuscação estruturada de URL",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "base64 na URL + domínio novo — possível entrega de payload ofuscado",
        },
    ],
    "xss_pattern": [
        {
            "depends_on": "mix_encoding",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.7,
            "reason": "sem encoding misto, padrão XSS tem menor chance de ser exploração real",
        },
        {
            "depends_on": "query_contains_url",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "padrão XSS + URL na query — possível ataque de redirecionamento com payload",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "padrão XSS + domínio novo — infraestrutura de ataque recém-criada",
        },
    ],
    "image_src_check": [
        {
            "depends_on": "external_script",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.4,
            "reason": "sem scripts externos suspeitos, imagem externa tem baixo valor diagnóstico",
        },
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is not None and v >= 1.0,
            "action": "increase",
            "factor": 1.3,
            "reason": "imagens externas + form action externo — clonagem de site legítimo provável",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "imagens externas + domínio novo — possível clone de site legítimo",
        },
    ],
    "favicon_check": [
        {
            "depends_on": "external_script",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.4,
            "reason": "sem scripts externos, favicon externo tem baixo valor diagnóstico",
        },
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.5,
            "reason": "sem form action externo, favicon externo é menos relevante",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is not None and v >= 1.0,
            "action": "increase",
            "factor": 1.4,
            "reason": "favicon externo + senha — possível clone de site legítimo para coleta",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "favicon externo + domínio novo — clone de identidade visual em infraestrutura recente",
        },
    ],
    "path_depth_risk": [
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.5,
            "reason": "sem segmentos suspeitos no path, profundidade é menos relevante",
        },
        {
            "depends_on": "base64_segment",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "path profundo + base64 — estrutura de URL obfuscada",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "path profundo + domínio novo — URL complexa em infraestrutura descartável",
        },
    ],
}