DEPENDENCIES: dict[str, list[dict]] = {

    "ssl_score": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.1,
            "reason": "domínio muito antigo com SSL suspeito — provável renovação ou CDN com cert separado",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.35,
            "reason": "domínio estabelecido com SSL moderado — infraestrutura consolidada",
        },
        {
            "depends_on": "dns_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "SSL moderado + DNS saudável — infraestrutura estabelecida",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.35,
            "reason": "SSL suspeito em domínio reconhecível — provável misconfiguration pontual",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.5,
            "reason": "SSL inválido + domínio novo — combinação de alto risco",
        },
        {
            "depends_on": "dns_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "SSL inválido + DNS suspeito — infraestrutura completamente comprometida",
        },
        {
            "depends_on": "ip_in_url",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "SSL inválido + IP no lugar do hostname — infraestrutura descartável",
        },
    ],

    "domain_age": [
        {
            "depends_on": "dns_score",
            "condition": lambda v: v is None,
            "action": "skip",
            "reason": "DNS falhou — domain age não pode ser confirmado",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "domínio novo + SSL inválido — infraestrutura de phishing típica",
        },
        {
            "depends_on": "dns_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "domínio novo + DNS suspeito — infraestrutura descartável confirmada",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.6,
            "action": "increase",
            "factor": 1.3,
            "reason": "domínio novo + nome aleatório — padrão DGA ou geração automática",
        },
        {
            "depends_on": "rdap_metadata_incompleteness",
            "condition": lambda v: v is not None and v >= 0.6,
            "action": "increase",
            "factor": 1.2,
            "reason": "domínio novo + RDAP incompleto — registro anônimo recente",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "domínio novo mas SSL válido de CA estabelecida — serviço legítimo recém-lançado",
        },
        {
            "depends_on": "dns_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.45,
            "reason": "domínio novo mas DNS saudável — site legítimo recém-lançado",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "domínio novo mas nome reconhecível — produto ou serviço recém-lançado",
        },
    ],

    "dns_score": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "DNS suspeito em domínio muito antigo — CDN ou balanceamento legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.5,
            "reason": "DNS suspeito em domínio estabelecido — configuração não convencional mas legítima",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.15,
            "action": "reduce",
            "factor": 0.25,
            "reason": "DNS sem MX + SSL completamente válido — site estático legítimo",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "DNS suspeito em domínio reconhecível — infraestrutura não convencional legítima",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.9,
            "action": "increase",
            "factor": 1.4,
            "reason": "DNS suspeito + SSL completamente inválido — infraestrutura completamente suspeita",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.7,
            "action": "increase",
            "factor": 1.2,
            "reason": "DNS suspeito + SSL inválido — múltiplos sinais de infraestrutura maliciosa",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "DNS suspeito + domínio novo — padrão de infraestrutura descartável",
        },
        {
            "depends_on": "ip_in_url",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "DNS suspeito + IP no hostname — servidor sem identidade de domínio",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.6,
            "action": "increase",
            "factor": 1.2,
            "reason": "DNS suspeito + domínio aleatório — possível domínio DGA",
        },
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.15,
            "reason": "DNS suspeito + path suspeito — servidor malicioso com URL estruturada para evasão",
        },
    ],

    "rdap_metadata_incompleteness": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "RDAP incompleto em domínio muito antigo — dados podem ter sido removidos por privacidade",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "RDAP incompleto mas SSL válido — privacidade de registro em serviço legítimo",
        },
        {
            "depends_on": "dns_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.45,
            "reason": "RDAP incompleto mas DNS saudável — registro com privacidade em serviço legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "RDAP incompleto + domínio novo — registro anônimo recente típico de phishing",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "RDAP incompleto + SSL inválido — infraestrutura sem identidade verificável",
        },
        {
            "depends_on": "nameserver_diversity",
            "condition": lambda v: v is not None and v >= 0.7,
            "action": "increase",
            "factor": 1.2,
            "reason": "RDAP incompleto + nameserver único — infraestrutura mínima descartável",
        },
    ],

    "nameserver_diversity": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "nameserver único em domínio muito antigo — provedor DNS consolidado legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.4,
            "reason": "nameserver único em domínio estabelecido — provedor DNS único legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "nameserver único mas SSL válido — CDN com DNS centralizado legítimo",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.45,
            "reason": "nameserver único em domínio reconhecível — serviço legítimo com DNS centralizado",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "nameserver único + domínio novo — infraestrutura mínima descartável",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "nameserver único + SSL inválido — infraestrutura descartável sem configuração adequada",
        },
        {
            "depends_on": "rdap_metadata_incompleteness",
            "condition": lambda v: v is not None and v >= 0.6,
            "action": "increase",
            "factor": 1.2,
            "reason": "nameserver único + RDAP incompleto — identidade de domínio completamente opaca",
        },
    ],

    "hyphen_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "hífens em domínio muito antigo — nome legítimo consolidado",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.4,
            "reason": "hífens em domínio estabelecido — nome descritivo legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "hífens mas SSL válido — domínio descritivo legítimo",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "hífens em domínio com baixa entropia — nome descritivo intencional",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.25,
            "reason": "hífens + domínio novo — padrão de domínio gerado automaticamente",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "hífens + entropia alta — padrão de geração automática confirmado",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "hífens + SSL inválido — domínio descartável sem infraestrutura adequada",
        },
        {
            "depends_on": "num_ratio_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "hífens + proporção alta de números — padrão DGA combinado",
        },
    ],

    "at_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "@ em domínio muito antigo — credencial legítima em URL interna",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.15,
            "action": "reduce",
            "factor": 0.3,
            "reason": "@ na URL mas SSL completamente válido — autenticação básica legítima",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.5,
            "reason": "@ na URL + domínio novo — bypass de hostname via credencial falsa",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.7,
            "action": "increase",
            "factor": 1.4,
            "reason": "@ na URL + SSL inválido — técnica clássica de ofuscação de destino",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "@ na URL + domínio aleatório — URL de phishing com hostname ofuscado",
        },
        {
            "depends_on": "ip_in_url",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.5,
            "reason": "@ na URL + IP no hostname — técnica de ofuscação de destino confirmada",
        },
    ],

    "equal_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "= suspeito em domínio muito antigo — parâmetros de API legítimos",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.35,
            "reason": "= suspeito mas SSL válido — parâmetros de query legítimos",
        },
        {
            "depends_on": "mixed_encoding",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "= suspeito + encoding misto — obfuscação de parâmetros",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "= suspeito + domínio novo — parâmetros de payload em infraestrutura descartável",
        },
        {
            "depends_on": "xss_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "= suspeito + padrão XSS — injeção via parâmetro confirmada",
        },
        {
            "depends_on": "query_contains_url",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "= suspeito + URL na query — estrutura de open redirect com parâmetro ofuscado",
        },
    ],

    "num_ratio_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "proporção alta de números em domínio muito antigo — nome legítimo estabelecido",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.4,
            "reason": "números em domínio estabelecido — identificador numérico legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "números no domínio mas SSL válido — serviço legítimo com nome numérico",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "números mas entropia baixa — domínio estruturado intencionalmente",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "números + domínio novo — padrão de geração automática",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "números + entropia alta — domínio com perfil DGA",
        },
        {
            "depends_on": "hyphen_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "números + hífens — combinação típica de domínio gerado automaticamente",
        },
    ],

    "mixed_encoding": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "encoding misto em domínio muito antigo — internacionalização legítima",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.35,
            "reason": "encoding misto mas SSL válido — internacionalização em serviço legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "encoding misto + domínio novo — obfuscação intencional em infraestrutura descartável",
        },
        {
            "depends_on": "xss_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.5,
            "reason": "encoding misto + padrão XSS — evasão de filtros com payload ofuscado",
        },
        {
            "depends_on": "base64_segment",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "encoding misto + base64 — múltiplas camadas de ofuscação",
        },
        {
            "depends_on": "at_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "encoding misto + @ na URL — ofuscação de destino em múltiplas camadas",
        },
    ],

    "xss_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "padrão XSS em domínio muito antigo — falso positivo em campo de busca legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.15,
            "action": "reduce",
            "factor": 0.3,
            "reason": "padrão XSS mas SSL completamente válido — parâmetro de teste legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "padrão XSS + domínio novo — infraestrutura de ataque recém-criada",
        },
        {
            "depends_on": "mixed_encoding",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.5,
            "reason": "padrão XSS + encoding misto — payload ofuscado para evasão de filtros",
        },
        {
            "depends_on": "query_contains_url",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "padrão XSS + URL na query — ataque de redirecionamento com payload",
        },
        {
            "depends_on": "equal_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "padrão XSS + = suspeito — injeção via parâmetro estruturada",
        },
    ],

    "ip_in_url": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "IP no hostname em domínio muito antigo — acesso interno legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.15,
            "action": "reduce",
            "factor": 0.25,
            "reason": "IP no hostname mas SSL completamente válido — serviço interno com cert válido",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.7,
            "action": "increase",
            "factor": 1.5,
            "reason": "IP no hostname + SSL inválido — servidor sem identidade verificável",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "IP no hostname + domínio novo — infraestrutura descartável sem DNS estabelecido",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.6,
            "reason": "IP no hostname + campo de senha — credential harvesting em servidor sem identidade",
        },
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "IP no hostname + path suspeito — servidor anônimo com URL estruturada para evasão",
        },
    ],

    "subdomain_count": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "múltiplos subdomínios em domínio muito antigo — plataforma cloud estabelecida",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.35,
            "reason": "múltiplos subdomínios com SSL válido — plataforma cloud legítima com wildcard cert",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "múltiplos subdomínios em domínio reconhecido — estrutura de plataforma cloud legítima",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "múltiplos subdomínios + domínio novo — infraestrutura descartável em cloud",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "múltiplos subdomínios + SSL inválido — cloud storage phishing sem configuração adequada",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "muitos subdomínios + subdomínio suspeito — padrão de phishing em cloud",
        },
        {
            "depends_on": "dns_score",
            "condition": lambda v: v is not None and v >= 0.6,
            "action": "increase",
            "factor": 1.2,
            "reason": "múltiplos subdomínios + DNS sem MX — site descartável em cloud",
        },
    ],

    "random_domain_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.05,
            "reason": "domínio muito antigo com entropia alta — marca consolidada ou sigla",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.2,
            "reason": "domínio estabelecido com alta entropia — provável marca legítima",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.15,
            "action": "reduce",
            "factor": 0.2,
            "reason": "entropia alta mas SSL completamente válido de CA estabelecida — serviço legítimo",
        },
        {
            "depends_on": "dns_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.35,
            "reason": "entropia alta mas DNS saudável com MX — empresa legítima com nome incomum",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "domínio aleatório + recém-criado — padrão DGA ou geração automática",
        },
        {
            "depends_on": "dns_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "domínio aleatório + infraestrutura DNS mínima — descartável",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "domínio aleatório + SSL inválido — infraestrutura de phishing descartável",
        },
    ],

    "random_subdomain_risk": [
        {
            "depends_on": "subdomain_count",
            "condition": lambda v: v is None,
            "action": "skip",
            "reason": "sem subdomínios detectados",
        },
        {
            "depends_on": "subdomain_count",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "subdomínio suspeito + contagem alta — padrão de phishing em cloud confirmado",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "subdomínio suspeito em domínio muito antigo — plataforma cloud estabelecida",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "subdomínio suspeito mas SSL válido em domínio estabelecido — plataforma de hosting legítima",
        },
        {
            "depends_on": "dns_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "subdomínio suspeito mas DNS saudável — plataforma cloud legítima",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "reduce",
            "factor": 0.5,
            "reason": "domínio base já sinalizado como aleatório — sinal redundante, não amplificar",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "subdomínio suspeito + domínio novo — phishing em plataforma cloud recém-criada",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.5,
            "reason": "subdomínio suspeito + campo de senha — credential harvesting em plataforma",
        },
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is not None and v >= 0.4,
            "action": "increase",
            "factor": 1.3,
            "reason": "subdomínio suspeito + path suspeito — URL de phishing estruturada em plataforma",
        },
    ],

    "random_path_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "path aleatório em domínio muito antigo — token ou ID de sessão legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.4,
            "reason": "path aleatório em domínio estabelecido — hash de conteúdo ou UUID legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.35,
            "reason": "path aleatório mas SSL válido em domínio reconhecível — ID de recurso legítimo",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "path aleatório em domínio reconhecível — UUID ou token de acesso legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "path aleatório + domínio novo — URL descartável típica de campanha de phishing",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "path aleatório + SSL inválido — infraestrutura de entrega de payload",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "path aleatório + domínio aleatório — URL inteiramente gerada automaticamente",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "path aleatório + campo de senha — credential harvesting com URL descartável",
        },
    ],

    "query_no_value": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "parâmetros vazios em domínio muito antigo — feature flags ou tracking legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "parâmetros vazios mas SSL válido — feature flags legítimos",
        },
        {
            "depends_on": "query_contains_url",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "parâmetros vazios + URL na query — estrutura de open redirect com evasão",
        },
        {
            "depends_on": "mixed_encoding",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "parâmetros vazios + encoding misto — obfuscação de parâmetros",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "parâmetros vazios + domínio novo — URL de phishing com estrutura incompleta",
        },
    ],

    "query_contains_url": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "URL na query em domínio muito antigo — parâmetro de redirect OAuth legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.15,
            "action": "reduce",
            "factor": 0.25,
            "reason": "URL na query mas SSL completamente válido — OAuth ou redirect legítimo",
        },
        {
            "depends_on": "mixed_encoding",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "URL na query + encoding misto — obfuscação intencional de destino",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "URL na query + domínio novo — open redirect em infraestrutura descartável",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.7,
            "action": "increase",
            "factor": 1.3,
            "reason": "URL na query + SSL inválido — redirecionamento para destino não verificável",
        },
        {
            "depends_on": "at_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "URL na query + @ na URL — dupla ofuscação de destino",
        },
    ],

    "base64_segment": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "base64 em domínio muito antigo — token de autenticação legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "base64 mas SSL válido em domínio estabelecido — dado codificado legítimo na URL",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "base64 na URL + domínio novo — entrega de payload ofuscado",
        },
        {
            "depends_on": "mixed_encoding",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "base64 + encoding misto — múltiplas camadas de ofuscação na URL",
        },
        {
            "depends_on": "path_depth_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "base64 + path profundo — estrutura de URL obfuscada",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "base64 + SSL inválido — payload ofuscado em infraestrutura comprometida",
        },
    ],

    "path_depth_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "path profundo em domínio muito antigo — estrutura de rotas de aplicação legítima",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "path profundo mas SSL válido — rotas de API ou CMS legítimo",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.35,
            "reason": "path profundo em domínio reconhecível — estrutura de aplicação legítima",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "path profundo + domínio novo — URL complexa em infraestrutura descartável",
        },
        {
            "depends_on": "base64_segment",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "path profundo + base64 — estrutura de URL obfuscada",
        },
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "path profundo + segmentos aleatórios — URL inteiramente construída para evasão",
        },
    ],

    "fragment_risk": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "fragmento suspeito em domínio muito antigo — SPA com roteamento via hash",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "fragmento suspeito mas SSL válido — roteamento de SPA legítimo",
        },
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "fragmento suspeito mas path normal — fragmento isolado é menos indicativo",
        },
        {
            "depends_on": "xss_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "fragmento suspeito + padrão XSS — injeção via hash da URL",
        },
        {
            "depends_on": "mixed_encoding",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "fragmento suspeito + encoding misto — obfuscação de payload no hash",
        },
        {
            "depends_on": "random_path_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "fragmento suspeito + path aleatório — URL de payload completamente ofuscada",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "fragmento suspeito + domínio novo — URL de phishing com fragmento como payload",
        },
    ],

    "external_script": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "scripts externos em domínio muito antigo — CDN ou biblioteca legítima",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "scripts externos mas SSL válido em domínio estabelecido — CDN legítimo",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "scripts externos em domínio reconhecível — analytics ou CDN legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "scripts externos + domínio novo — infraestrutura de ataque recente",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "scripts externos + SSL inválido — múltiplos sinais de comprometimento",
        },
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "scripts externos + form action externo — credential harvesting provável",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "scripts externos + campo de senha — possível keylogger ou exfiltração via script",
        },
    ],

    "favicon_check": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "favicon externo em domínio muito antigo — CDN de ícones legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "favicon externo mas SSL válido — uso de CDN legítimo",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.4,
            "reason": "favicon externo em domínio reconhecível — CDN de ícones legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.7,
            "action": "increase",
            "factor": 1.3,
            "reason": "favicon externo + SSL inválido — clone de identidade visual em infraestrutura comprometida",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "favicon externo + campo de senha — clone de site legítimo para coleta de credenciais",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "favicon externo + domínio novo — clone de identidade visual em infraestrutura recente",
        },
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "favicon externo + form action externo — clonagem completa de site legítimo",
        },
    ],

    "image_src_check": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "imagens externas em domínio muito antigo — CDN de imagens legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "imagens externas mas SSL válido — CDN legítimo",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.35,
            "reason": "imagens externas em domínio reconhecível — CDN de imagens legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "imagens externas + domínio novo — clone de site legítimo",
        },
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "imagens externas + form action externo — clonagem de site legítimo provável",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "imagens externas + campo de senha — clone de login de serviço legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.15,
            "reason": "imagens externas + SSL inválido — clone de site em infraestrutura comprometida",
        },
    ],

    "redirect_check": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "redirect em domínio muito antigo — redirecionamento estrutural legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "redirect mas SSL válido em domínio estabelecido — redirect HTTP→HTTPS legítimo",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.3,
            "action": "reduce",
            "factor": 0.5,
            "reason": "redirect em domínio não aleatório — redirecionamento estrutural legítimo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "redirect externo + domínio novo — evasão de detecção provável",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "redirect externo + SSL inválido — evasão com infraestrutura comprometida",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "redirect externo + campo de senha — evasão de detecção antes de coleta de credenciais",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.2,
            "reason": "redirect externo + subdomínio suspeito — evasão via plataforma cloud",
        },
    ],

    "hidden_fields_check": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "campos ocultos em domínio muito antigo — tokens CSRF ou dados de sessão legítimos",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "campos ocultos mas SSL válido — campos de rastreamento legítimos",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.35,
            "reason": "campos ocultos em domínio reconhecível — campos de formulário legítimos",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.3,
            "reason": "campos ocultos + SSL inválido — exfiltração de dados sem proteção",
        },
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "campos ocultos + form action externo — exfiltração de dados provável",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.3,
            "reason": "campos ocultos + campo de senha — formulário de coleta de credenciais completo",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.2,
            "reason": "campos ocultos + domínio novo — exfiltração em infraestrutura descartável",
        },
    ],

    "password_input_check": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.05,
            "action": "reduce",
            "factor": 0.1,
            "reason": "campo de senha em domínio muito estabelecido — página de login legítima",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "campo de senha em domínio estabelecido — login legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.15,
            "reason": "campo de senha com SSL completamente válido — página de login segura",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "campo de senha em domínio reconhecível — login de serviço legítimo",
        },
        {
            "depends_on": "form_action_check",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.85,
            "reason": "sem form action externo, campo de senha é levemente menos crítico",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "campo de senha + SSL inválido — coleta de credenciais sem proteção",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.4,
            "reason": "campo de senha + domínio novo — credential harvesting em site descartável",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.5,
            "reason": "campo de senha + subdomínio suspeito — credential harvesting em plataforma",
        },
        {
            "depends_on": "ip_in_url",
            "condition": lambda v: v is not None and v >= 0.7,
            "action": "increase",
            "factor": 1.5,
            "reason": "campo de senha + IP no hostname — coleta de credenciais em servidor anônimo",
        },
    ],

    "form_action_check": [
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v < 0.1,
            "action": "reduce",
            "factor": 0.2,
            "reason": "form action externo em domínio muito antigo — integração com CRM ou pagamento legítimo",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.3,
            "reason": "form action externo mas SSL válido — integração legítima com serviço externo",
        },
        {
            "depends_on": "random_domain_risk",
            "condition": lambda v: v is not None and v < 0.2,
            "action": "reduce",
            "factor": 0.35,
            "reason": "form action externo em domínio reconhecível — integração com serviço legítimo",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is None,
            "action": "reduce",
            "factor": 0.5,
            "reason": "sem campo de senha, form action externo é menos crítico",
        },
        {
            "depends_on": "ssl_score",
            "condition": lambda v: v is not None and v >= 0.8,
            "action": "increase",
            "factor": 1.5,
            "reason": "form action externo + SSL inválido — coleta de dados sem proteção confirmada",
        },
        {
            "depends_on": "domain_age",
            "condition": lambda v: v is not None and v > 0.8,
            "action": "increase",
            "factor": 1.5,
            "reason": "form action externo + domínio novo — coleta de credenciais em site descartável",
        },
        {
            "depends_on": "password_input_check",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.5,
            "reason": "form action externo + campo de senha — credential harvesting confirmado",
        },
        {
            "depends_on": "random_subdomain_risk",
            "condition": lambda v: v is not None and v >= 0.5,
            "action": "increase",
            "factor": 1.4,
            "reason": "form action externo + subdomínio suspeito — coleta de dados em plataforma cloud",
        },
        {
            "depends_on": "ip_in_url",
            "condition": lambda v: v is not None and v >= 0.7,
            "action": "increase",
            "factor": 1.4,
            "reason": "form action externo + IP no hostname — envio de dados para servidor anônimo",
        },
    ],
}